version: '3.8'

services:
  crawl-browser:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9222:9222"  # Chrome DevTools Protocol
      - "7900:7900"  # noVNC (optional for debugging)
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:9222/json/version | grep -q 'Browser'"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 30s

  test-runner:
    build:
      context: ./tests
      dockerfile: Dockerfile.tests
    depends_on:
      crawl-browser:
        condition: service_healthy
    environment:
      - CDP_ENDPOINT=http://crawl-browser:9222
      - TEST_TIMEOUT=60000
      - NODE_ENV=test
      - DEBUG=pw:api
    volumes:
      - ./test-results:/app/test-results
      - ./tests:/app/tests:ro
    networks:
      - test-network
    command: npm test

networks:
  test-network:
    driver: bridge
