services:
  crawl-browser:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "9222:9222"  # Chrome DevTools Protocol
      - "7900:7900"  # noVNC (optional for debugging)
    networks:
      - test-network
    environment:
      - CHROME_EXTENSIONS=mm|https://github.com/MetaMask/metamask-extension/releases/download/v12.22.3/metamask-flask-chrome-12.22.3-flask.0.zip,bpc|https://gitflic.ru/project/magnolia1234/bpc_uploads/blob/raw?file=bypass-paywalls-chrome-clean-master.zip|bypass-paywalls-chrome-clean-master,justread|https://github.com/ZachSaucier/Just-Read/archive/master.zip|Just-Read-master

  test-runner:
    build:
      context: ../tests
      dockerfile: Dockerfile.tests
    depends_on:
      crawl-browser:
        condition: service_healthy
    environment:
      - CDP_ENDPOINT=http://crawl-browser:9222
      - TEST_TIMEOUT=60000
      - NODE_ENV=test
      - DEBUG=pw:api
      - HAS_METAMASK=true
    volumes:
      - ../tests:/app/tests:ro
    networks:
      - test-network
    command: npm test

networks:
  test-network:
    driver: bridge
